CREATE SEQUENCE IF NOT EXISTS client_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS client
(
    id   BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS address
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    street    VARCHAR(255),
    client_id BIGINT UNIQUE
);

CREATE TABLE IF NOT EXISTS phone
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    number    VARCHAR(50),
    client_id BIGINT
);